### ISSUE TITLE
Outlook on iOS iPhone 5 text too small

### ISSUE THREAD

**Issue by jeffmcneill** [julie-ng/gmail-first-gutters-demo#1]
I like this project, but it doesn't seem to pan out with several clients, but in particular Outlook on iOS on the iPhone 5, the text is too small. Also it is too large on the desktop (Nylas N1)

**\- Image Magic on iOS**

![img_0777](https://cloud.githubusercontent.com/assets/3119827/15797467/ee7fad7a-2a43-11e6-87d0-da2ad3391666.PNG)

---

**\- iOS Mail**

![img_0776](https://cloud.githubusercontent.com/assets/3119827/15797468/ee7f873c-2a43-11e6-9330-ca50aa6f9cc6.PNG)

---

**\- Gmail on iOS**

![img_0775](https://cloud.githubusercontent.com/assets/3119827/15797466/ee7f71de-2a43-11e6-9e10-ec9de665413f.PNG)

---

**\- Outlook on iOS**

![img_0773](https://cloud.githubusercontent.com/assets/3119827/15797469/ee89da70-2a43-11e6-923d-1afc685b7485.PNG)

---

**\- Chrome on iOS**

![img_0778](https://cloud.githubusercontent.com/assets/3119827/15797473/f67e6cd2-2a43-11e6-914d-47ca03c8f0f6.PNG)

---

**Nylas N1 on OSX**

![screen shot 2016-06-04 at 11 04 05](https://cloud.githubusercontent.com/assets/3119827/15797478/1c8d08c0-2a44-11e6-9fa9-7fa8dc5f2626.png)

I want to approximate the website this is on (see Chrome on iOS iphone 5 + desktop screen shots). I have a decent bootstrap-based system for responsive web. Would really like to get an improved version of your system to better match font size (baby-bear just right) on all mobile email clients as well as desktop mail clients.

**Comment by julie-ng** [comment]
Hi Jeff, 

I agree, the font sizes are not ideal. But this demo was mostly for layouts. Feel free to customize the font size to suit your needs - especially with media queries for different screen sizes.

Yes, the intro paragraph font is not ideal - too large for the amount of text that is there.

Cheers
Julie

**Comment by jeffmcneill** [comment]
I guess I didn't explain. The point is that a single font size using your layouts does not work, as Outlook on IOS doesn't render in the same way. This means that the layouts/media quieries is not working properly, and that using your layouts/framework there is something not well supported, aka a BUG.

**Comment by julie-ng** [comment]
Sorry, I think there's another misunderstanding here. This is **not a framework** - just a code demo responsive **layouts**.

Because the font size isn't layout, I am not addressing this here. In the future, I might consider another demo just for font sizes.
